### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ghost** [csv-viewer-online/csv-viewer-online.github.io#1]
can you turn this into a csv viewer for windows?
excel sucks, and refuses to correctly view csv files that include japanese characters
yours seems to do it just fine

**Comment by limonte** [comment]
You can save the CSV viewer to your PC and use it offline:

![image](https://user-images.githubusercontent.com/6059356/103086412-3d1fec00-45ed-11eb-989f-3b88254b9868.png)
