### ISSUE TITLE
Top rows aren't visible

### ISSUE THREAD

**Issue by vaibhav-zwayam** [csv-viewer-online/csv-viewer-online.github.io#2]
I've been using the tool and it's very helpful but a lot of times the top rows aren't visible. You can see a screengrab of the same here: https://i.imgur.com/9UaBzYh.png

I have tried different browsers (Firefox, Edge and Chrome to be specific) and the issue persists.

**Comment by limonte** [comment]
Fixed, thanks for reporting!
