### ISSUE TITLE
Encoding - UTF8 expected

### ISSUE THREAD

**Issue by hausl** [csv-viewer-online/csv-viewer-online.github.io#4]
If i have a CSV in ISO-8859-1 ("Latin 1") encoding with german umlauts (ä ö ü ß) then it is not correct displayed.
Have manually convert the file to UTF 8 then its ok.
![IMG_092207](https://github.com/csv-viewer-online/csv-viewer-online.github.io/assets/5177282/1efb0630-f227-40da-b0d0-f7c85db68fbb)
![IMG_092218](https://github.com/csv-viewer-online/csv-viewer-online.github.io/assets/5177282/b8b9b5c0-6412-45cc-b688-7ecba78ce36f)

**Comment by limonte** [comment]
Thanks for reporting, but I'll close this issue as wontfix.

It's technically possible to add the encoding detection, but that may result in unexpected side-effects and the code complexity will also grow. 

Since UTF-8 is the standard nowadays, I'd keep this app as it is.

**Comment by hausl** [comment]
ok, thank you!
